export const SAVED_LOCATION_ICONS = [
    "archive",
    "asterisk",
    "bell",
    "bookmark",
    "box",
    "briefcase",
    "building",
    "bullseye",
    "calendar",
    "camera",
    "cart",
    "cloud",
    "cloud download",
    "code",
    "cog",
    "cube",
    "cubes",
    "database",
    "desktop",
    "download",
    "file",
    "file outline",
    "film",
    "flag",
    "folder",
    "folder open",
    "gamepad",
    "gift",
    "globe",
    "hdd",
    "heart",
    "home",
    "image",
    "inbox",
    "key",
    "lab",
    "leaf",
    "life ring",
    "lightbulb",
    "lock",
    "magic",
    "map",
    "marker",
    "moon",
    "music",
    "paper plane",
    "paw",
    "photo",
    "picture",
    "rocket",
    "save",
    "server",
    "setting",
    "ship",
    "shopping bag",
    "sitemap",
    "star",
    "suitcase",
    "tag",
    "trophy",
    "truck",
    "university",
    "user",
    "video camera",
    "world",
    "wrench",
];
