import type { TorrentClientFeatures } from "../../../src/shared/ipc-contract"
import type { TestClient } from "../types"
import { defineClient } from "../define"

const features = {
  magnetLinks: true,
  labels: true,
  fileSelection: true,
  filePriorities: [
    { id: "skip", label: "Skip", value: 0, wanted: false },
    { id: "normal", label: "Normal", value: 1, wanted: true },
    { id: "high", label: "High", value: 6, wanted: true },
    { id: "maximum", label: "Maximum", value: 7, wanted: true },
  ],
  uploadFileSelection: true,
  setLocation: true,
  torrentDetails: true,
  torrentPeers: true,
  torrentTrackers: true,
  trackerFilter: true,
  alternativeSpeedLimits: true,
  speedLimits: true,
  ratioLimits: true,
  freeDiskSpace: true,
  uploadOptions: {
    saveLocation: true,
    renameTorrent: true,
    category: true,
    startTorrent: true,
    skipCheck: true,
    sequentialDownload: true,
    firstAndLastPiecePrio: true,
    downloadSpeedLimit: true,
    uploadSpeedLimit: true,
  },
} satisfies TorrentClientFeatures

const legacyFeatures = {
  ...features,
  alternativeSpeedLimits: false,
  ratioLimits: false,
  trackerFilter: false,
  torrentPeers: false,
  torrentTrackers: false,
  uploadFileSelection: false,
} satisfies TorrentClientFeatures

const basicAuthSpecs = [
  "test/specs/qbittorrent/http-basic-auth.spec.ts",
]

export default {
  "qbittorrent:http-basic-auth": defineClient({
    key: "qbittorrent:http-basic-auth",
    clientId: "qbittorrent",
    features,
    fixture: "clients/qbittorrent",
    version: "latest",
    port: 58080,
    containerPort: 8080,
    containerHostPort: 58081,
    proxyPort: 8080,
    authProxyHostPort: 58080,
    authProxyPasswordFile: "qbittorrent-basic-auth.htpasswd",
    username: "admin",
    password: "adminadmin",
    specs: basicAuthSpecs,
    downloadRoot: "/downloads",
  }),
  "qbittorrent:4.1": defineClient({
    key: "qbittorrent:4.1",
    clientId: "qbittorrent",
    features: legacyFeatures,
    fixture: "clients/qbittorrent",
    version: "amd64-4.1.5.99201812282032-6681-264b689ubuntu18.04.1-ls1",
    port: 48080,
    containerPort: 8080,
    username: "admin",
    password: "adminadmin",
    downloadRoot: "/downloads",
  }),
  "qbittorrent:4": defineClient({
    key: "qbittorrent:4",
    clientId: "qbittorrent",
    features,
    fixture: "clients/qbittorrent",
    version: "4.6.7",
    port: 18080,
    containerPort: 8080,
    username: "admin",
    password: "adminadmin",
    downloadRoot: "/downloads",
  }),
  "qbittorrent:5": defineClient({
    key: "qbittorrent:5",
    clientId: "qbittorrent",
    features,
    fixture: "clients/qbittorrent",
    version: "5.1.0",
    port: 28080,
    containerPort: 8080,
    username: "admin",
    password: "adminadmin",
    downloadRoot: "/downloads",
  }),
  "qbittorrent:latest": defineClient({
    key: "qbittorrent:latest",
    clientId: "qbittorrent",
    features,
    fixture: "clients/qbittorrent",
    version: "latest",
    port: 38080,
    containerPort: 8080,
    username: "admin",
    password: "adminadmin",
    downloadRoot: "/downloads",
  }),
} satisfies Record<string, TestClient>
